# Generated by Django 5.2.8 on 2025-11-25 05:00

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(help_text='Formato internacional, ej: +56912345678', max_length=128, region=None, unique=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('preferencias', models.CharField(choices=[('NINGUNA', 'Ninguna'), ('VEGETARIANO', 'Vegetariano'), ('VEGANO', 'Vegano'), ('CELIACO', 'Celíaco'), ('OTRO', 'Otro')], default='NINGUNA', max_length=20)),
                ('detalle_preferencia', models.CharField(blank=True, max_length=100, null=True, verbose_name="Detalle de preferencia (si selecciona 'Otro')")),
                ('notas', models.TextField(blank=True, verbose_name='Observaciones (Alergias, Ocasiones)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número de Mesa')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad Personas (1-20)')),
                ('ubicacion', models.CharField(choices=[('SALA', 'Sala Principal'), ('TERRAZA', 'Terraza'), ('PRIVADO', 'Privado')], default='SALA', max_length=20)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('RESERVADA', 'Reservada'), ('LIMPIEZA', 'En Limpieza')], default='LIBRE', max_length=20)),
                ('ultima_ocupacion_inicio', models.DateTimeField(blank=True, null=True)),
                ('ultima_liberacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha Reserva')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(help_text='Duración estimada', verbose_name='Hora Fin')),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('LLEGO', 'Cliente Llegó'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='CONFIRMADA', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='MainApp.cliente')),
                ('mesa_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_futuras', to='MainApp.mesa')),
            ],
        ),
    ]
