# Generated by Django 5.2.8 on 2025-11-25 06:46

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesa',
            old_name='ultima_liberacion',
            new_name='ultima_asignacion',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='created_at',
            new_name='creado_en',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='ultima_ocupacion_inicio',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='detalle_preferencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Detalle (Si es 'Otro')"),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Ej: +56912345678', max_length=128, region=None, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='capacidad',
            field=models.PositiveIntegerField(verbose_name='Capacidad Personas'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='ubicacion',
            field=models.CharField(help_text='Ej: Terraza, Sala Principal', max_length=50, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('LLEGO', 'Cliente Llegó'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mesa_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.mesa'),
        ),
        migrations.CreateModel(
            name='HistorialOcupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_entrada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('cantidad_personas', models.IntegerField(default=1)),
                ('consumo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.cliente')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.mesa')),
            ],
        ),
    ]
