# Generated by Django 5.2.8 on 2025-11-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_rename_ultima_liberacion_mesa_ultima_asignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='ubicacion',
            field=models.CharField(choices=[('SALA', 'Sala Principal'), ('TERRAZA', 'Terraza'), ('PRIVADO', 'Privado')], default='SALA', max_length=20, verbose_name='Ubicación'),
        ),
    ]
