# Generated by Django 5.2.8 on 2025-11-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_mesa_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('RESERVADA', 'Reservada'), ('LIMPIEZA', 'En Limpieza'), ('FUERA_SERVICIO', 'Fuera de Servicio')], default='LIBRE', max_length=20),
        ),
    ]
