# Generated by Django 5.2.8 on 2025-11-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacidad", models.IntegerField()),
                ("estado", models.CharField(default="Libre", max_length=20)),
                ("meseroId", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Ocupacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clienteId", models.IntegerField()),
                ("grupo", models.IntegerField(null=True)),
                ("tieneReserva", models.BooleanField(default=False)),
                ("horaAsignacion", models.DateTimeField(auto_now_add=True)),
                ("horaSalida", models.DateTimeField(blank=True, null=True)),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mesas.mesa"
                    ),
                ),
            ],
        ),
    ]
