# Generated by Django 5.2.8 on 2025-11-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mesas", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mesa",
            new_name="Mesas",
        ),
    ]
